### ISSUE TITLE
Unsupported Control Type: Rooflight (Dachfenster)

### ISSUE THREAD

**Issue by tom3737** [UncleSamSwiss/ioBroker.loxone#102]
Hi,

it would be great if the adapter could support rooflights, too. Thanks for the great work!

Tom

**Comment by UncleSamSwiss** [comment]
Thank you for your request.

Can you please provide the information as described here: https://github.com/UncleSamSwiss/ioBroker.loxone#bug-reports-and-feature-requests

I especially need the "raw" data to be able to do it without having the device myself.

**Comment by UncleSamSwiss** [comment]
Version 2.2 will support "unknown" controls. If you need additional functionality, please feel free to reopen this issue.
