### ISSUE TITLE
Fehlermeldung "unsupported state change"

### ISSUE THREAD

**Issue by Triple-M77** [UncleSamSwiss/ioBroker.loxone#117]
Ich nutze seid kurzem iobroker und u.a. auch den Loxone Adapter um ein paar Daten an Loxone zu übertragen. Ich habe dazu unter Loxone Config virtuelle Eingänge eingefügt und diese dann in iobroker per Javaskript verknüpft. Das klappt soweit auch ganz für allerdings habe ich dann bei diesen virtuellen Eingängen in der Loxone App immer die Anzeige für + und - drin, die ich eigentlich nicht brauche, da nur Werte angezeigt werden die nicht verändert werden in der App.

Wenn ich dann in der Loxone Condifg den Haken bei "nur Statusanzeige" setze, bekomme ich unter iobroker nach einer gewissen Zeit den Fehler "unsupported State change" und die Werte werden nicht mehr aktualisiert. Ist das ein Bug oder wie bekommt man diesen "Problem" weg?

![IMG_0365](https://user-images.githubusercontent.com/82801960/115200192-3bc28400-a0f4-11eb-9947-b6072eeac89a.jpeg)

![IMG_0053](https://user-images.githubusercontent.com/82801960/115200205-3f560b00-a0f4-11eb-84bc-9c470552fb97.jpeg)

![IMG_0054](https://user-images.githubusercontent.com/82801960/115200223-441abf00-a0f4-11eb-9c26-fbc3553373ff.jpeg)

![IMG_0056](https://user-images.githubusercontent.com/82801960/115200232-454bec00-a0f4-11eb-9b9d-f9efcf0fcbff.jpeg)

**Comment by Triple-M77** [comment]
Ich habe das ganze noch mal extra beobachtet. Gestern morgen habe ich in der Config den Haken gesetzt bei "nur Statusanzeige", das Projekt in den Miniserver geladen und die Aktualisierung hat den ganzen Tag bis heute morgen wunderbar funktioniert. Heute morgen dann dann das Project aus anderen Gründen etwas geändert und wieder hochgeladen und seid dem keine Aktualisierung mehr und im iobroker die Fehlermeldung.
Es hat also meiner Meinung nach bis zum erneuten Neustart des Miniserver's wunderbar funktioniert aber immer wenn man den Miniserver ein weiteres mal neu startet ist das Problem da.

![IMG_0060](https://user-images.githubusercontent.com/82801960/115361863-48f97480-a1c1-11eb-9bfa-f913991b19bc.jpeg)

**Comment by UncleSamSwiss** [comment]
Da der Adapter die WebSocket-Schnittstelle des Miniservers benutzt (die auch vom Web GUI benutzt wird), darf eine Variable nicht als "nur Statusanzeige" gesetzt werden, sonst kann der Adapter auch keine Werte mehr schreiben.

Was möglicherweise geht (kann ich bei mir nicht überprüfen): gib deinem normalen Benutzer (den du für die Weboberfläche nutzt) keine (Schreib-?)Rechte auf dem virtuellen Eingang.

**Comment by Triple-M77** [comment]
Ok, aber warum geht es dann längere Zeit ohne Probleme (Variable wird aktualisiert auch wenn „nur Statusanzeige“ angeklickt ist) und erst ein erneuter Neustart bringt das ganze zu dem bekannten Problem

**Comment by UncleSamSwiss** [comment]
Das Problem liegt wohl daran, dass du einen Datenpunkt beschreibst, der eigentlich read-only ist. Hast du mal den Datenpunkt genau angeschaut? Wie sieht das `native` vom Gerät darüber aus? Der Adapter ändert den Datenpunkt wohl erst bei einem Neustart.

Ich werde bald eine 2.2.1 machen, kannst du die dann installieren - dann sollte ich alle nötigen Telemetrie-Daten in Sentry erhalten um das Problem nochmals zu analysieren.

**Comment by Triple-M77** [comment]
Also ich bin leider nicht so versiert und verstehe nicht so ganz was du meinst. Der Datenpunkt wird allerdings min. stündlich aktualisiert.
