### ISSUE TITLE
Adapter causes reboot of Miniserver?

### ISSUE THREAD

**Issue by JochenKoehler** [UncleSamSwiss/ioBroker.loxone#12]
The IOBroker.loxone adapter was running in my building and I experienced some random reboots on the Miniserver. So I tried to deactivate IOBroker and no more unmotivated reboots. Is this possible? 
There are also some errors arising while the adapter is running:

loxone.0 | 2018-01-21 09:55:30.878 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
-- | -- | -- | --
loxone.0 | 2018-01-21 09:55:30.865 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
loxone.0 | 2018-01-21 09:55:30.852 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-01-21 09:55:30.851 | error | Unsupported control type Radio: ReferenceError: loadRadioControl is not defined
loxone.0 | 2018-01-21 09:55:30.850 | error | Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined
loxone.0 | 2018-01-21 09:55:30.848 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-01-21 09:55:30.848 | error | Unsupported control type Radio: ReferenceError: loadRadioControl is not defined
loxone.0 | 2018-01-21 09:55:30.846 | error | Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined
loxone.0 | 2018-01-21 09:55:30.845 | error | Unsupported control type Radio: ReferenceError: loadRadioControl is not defined
loxone.0 | 2018-01-21 09:55:30.845 | error | Unsupported control type Radio: ReferenceError: loadRadioControl is not defined
loxone.0 | 2018-01-21 09:55:30.841 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-01-21 09:55:30.837 | error | Unsupported control type UpDownDigital: ReferenceError: loadUpDownDigitalControl is not defined
loxone.0 | 2018-01-21 09:55:30.834 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-01-21 09:55:30.832 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-01-21 09:55:30.827 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
loxone.0 | 2018-01-21 09:55:30.764 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
loxone.0 | 2018-01-21 09:55:30.760 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-01-21 09:55:30.758 | error | Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined
loxone.0 | 2018-01-21 09:55:30.758 | error | Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined
loxone.0 | 2018-01-21 09:55:30.747 | error | Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined
loxone.0 | 2018-01-21 09:55:30.741 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
loxone.0 | 2018-01-21 09:55:30.663 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
loxone.0 | 2018-01-21 09:55:30.641 | error | Unsupported control type Radio: ReferenceError: loadRadioControl is not defined
loxone.0 | 2018-01-21 09:55:30.640 | error | Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined
loxone.0 | 2018-01-21 09:55:30.638 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
loxone.0 | 2018-01-21 09:55:30.603 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-01-21 09:55:30.598 | error | Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined
loxone.0 | 2018-01-21 09:55:30.554 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined

**Comment by UncleSamSwiss** [comment]
As far as I can tell, the errors have nothing to do with a Miniserver reboot (just features ioBroker doesn't support yet).
I'm pretty sure it is a Miniserver issue. Was the issue solved with a newer Miniserver version?

**Comment by UncleSamSwiss** [comment]
I'm assuming this has been solved one way or the other. Please let me know if this is not the case and I should reopen this issue.
