### ISSUE TITLE
Bump ioBroker repository to 2.2.0

### ISSUE THREAD

**Issue by 13az13** [UncleSamSwiss/ioBroker.loxone#134]
Please could you bump the ioBroker repository version so we can update to the latest release?  Many thanks for all your efforts, looking forward to being able to see the presence detector values

**Comment by UncleSamSwiss** [comment]
I will do this within a week.

In the meantime, you can install this version either by switching to the "Beta" channel or by installing it manually using the "Octocat" (cat) symbol in the adapter list, going to the right tab and entering "iobroker.loxone" (note: all lowercase).
