### ISSUE TITLE
Usage of "setObject" will overwrite custom-Settings and Cloud-Smartnames

### ISSUE THREAD

**Issue by Apollon77** [UncleSamSwiss/ioBroker.loxone#14]
It seems that the "hard" usage of "setObject" in your updateObject method casues all pot.set History-Settings (stored in "custom" of object) and also Cloud Smartnames and stuff get killed after each adapterstart.

Better is to use "extendObject" as soon as the object exists. If you can not tell that you should use getObject() and in callback according to result to use setObject and extendObject.

Forum see: http://forum.iobroker.net/viewtopic.php?p=124705#p124705

**Comment by Anubis2k** [comment]
Hi,

are there any updates for this issue?
Restarting the Loxone Adapter (e.g. Restart the Raspberry) will delete all manuel added smart devices from the Cloud Adapter.

**Comment by UncleSamSwiss** [comment]
Fixed with version 1.0.0 of the adapter.

**Comment by Apollon77** [comment]
Thank you

**Comment by akr1983** [comment]
Hi,

i've still got the issue. After a restart of the adapter, the SmartNames are disappearing from the Object. My Adapter is already Version 1.0.0. :-(
