### ISSUE TITLE
Unsupported control type: EIBDimmer

### ISSUE THREAD

**Issue by rhuitl** [UncleSamSwiss/ioBroker.loxone#15]
I'm trying to make KNX dimmers attached to Loxone available to ioBroker, but they do not show up as devices in ioBroker. The dimmers are present in Loxone Config as "EIB-Dimmer" Blocks. The log contains messages like this:

> error: loxone.0 Unsupported control type EIBDimmer: ReferenceError: loadEIBDimmerControl is not defined

There are also EIB Push Buttons ("EIB-Taster") which work out of the box. Seems like only the dimmers are unsupported. Is there any chance to get them supported? Why do the push buttons work, even though there is no "loadEIBPushButtonControl" (or similar) method defined in loxone.js?

**Comment by UncleSamSwiss** [comment]
Can you please provide the native value of this EIBDimmer?
See here for details: https://github.com/UncleSamSwiss/ioBroker.loxone#bug-reports-and-feature-requests

**Comment by rhuitl** [comment]
Hi Sam, yes it is:
```json
{
  "type": "state",
  "common": {
    "name": "Licht Schlafzimmer",
    "read": true,
    "write": false,
    "type": "string",
    "role": "text"
  },
  "native": {
    "name": "Licht Schlafzimmer",
    "type": "EIBDimmer",
    "uuidAction": "0a4f50d8-0359-add5-ffffeee000d811ab",
    "room": "0a48cae4-002b-001f-0f00000000000000",
    "cat": "0a48cae4-002b-0002-0d00000000000000",
    "defaultRating": 10,
    "isFavorite": true,
    "isSecured": false,
    "presence": true,
    "states": {
      "position": "0a4f50d8-0359-ade2-ffffeee000d811ab",
      "presenceFrom": "0ffcf2a3-0022-0c9a-ffffeee000d811ab",
      "presenceTo": "0ffcf2a3-0022-0c9b-ffffeee000d811ab"
    }
  },
  "from": "system.adapter.loxone.0",
  "ts": 1550005113815,
  "_id": "loxone.0.Unsupported.0a4f50d8-0359-add5-ffffeee000d811ab",
  "acl": {
    "object": 1638,
    "state": 1638
  }
}
```

Please note that the Loxone Miniserver I was using broke a while ago, the KNX interface has died. I do not need this to work anymore and unfortunately won't be able to test fixes. If nobody else needs it, we could close this ticket.

**Comment by 0x4D69636869** [comment]
Hi all,
I'm new to iobroker and need the EIBDimmer feature as well. My Miniserver is up and ready to test something :-)
BR
Michael

**Comment by MaverickElTech** [comment]
Hi all,
Is there already a solution? In node-red works! maybe this helps?
https://flows.nodered.org/node/node-red-contrib-loxone
BR
Daniel
