### ISSUE TITLE
Stabilitätsprobleme javascript mit loxone Adapter

### ISSUE THREAD

**Issue by razio80** [UncleSamSwiss/ioBroker.loxone#19]
Ich nutze ioBroker auf einem Tinkerboard mit Admin 3.5.0, js-controller 1.4.2 und loxone Adapter 0.4.0.
Mir ist aufgefallen, dass seit ich den Loxone-Adapter verwende, es Stabilitätsprobleme mit Scripten gibt.
Javascript stürzt öfter ab usw. 
Ich kann keine große Last auf dem Tinkerboard entdecken; ich denke also nicht, dass das Board überlastet ist.
Gibt es hierzu Erfahrungen, was man da machen kann?

**Comment by UncleSamSwiss** [comment]
Mit "grosse Last" meinst du nur die CPU oder auch RAM? Gerade bei grösseren Konfigurationen braucht der Loxone Adapter einiges an RAM. Meinst du den Javascript-Adapter oder wirklich den ioBroker Controller? Ich kann mir im Moment nicht vorstellen, was die Stabilität des js-controller mit dem Adapter zu tun haben könnte (beide laufen als separate Prozesse).
Kannst du neben dem RAM Verbrauch mal die Anzahl ein- und ausgehende Events anschauen und hier angeben? Eventuell gibt es einen Fehler, dass der Adapter viel zu viele Events generiert.
Siehst du im Log irgend etwas auffälliges? Eventuell mal das Log im Debug-Modus laufen lassen.
Welche Version von node.js verwendest du? Eine der offiziell unterstützten?

**Comment by razio80** [comment]
node -v
v6.14.4
npm -v
3.10.10

Sorry, ich meinte javascript schmiert ab.

CPU-Last und RAM-Auslastung sind eigentlich nicht der Rede wert.

Ich glaube auch an zu viele Events. Vielleicht liegt es daran, dass zu viele Events ankommen/abgehen.
Immer wenn ich den Adapter auf Debug stelle, läuft er erstmal. Daher habe ich momentan keine Log-Datei.
Übrigens nutze ich Loxone V10. Aber es war mit V9 genauso

**Comment by UncleSamSwiss** [comment]
Tritt das Problem immer noch auf?
Bei mir zu Hause habe ich die gesamte Logik im JavaScript Adapter implementiert und sehe die Probleme nicht (allerdings verwende ich auch nur 20 Loxone Touch (Tree und Air) und sonst keine weiteren Loxone Geräte).

**Comment by razio80** [comment]
Hi,

nein das Problem tritt nicht mehr auf, seitdem ich ioBroker auf redis
umgestellt habe. Vorher kamen wohl zu viele Informationen gleichzeitig,
sodass das System die Menge nicht mehr verarbeiten konnte.
Bei mir sind es mehr als doppelt so viele Loxone Geräte.

Btw, wird der Adapter noch weiterentwickelt?

Am So., 13. Jan. 2019 um 14:14 Uhr schrieb Samuel Weibel <
notifications@github.com>:

**Comment by UncleSamSwiss** [comment]
Besten Dank für dein Feedback. Gut zu wissen, dass es bei vielen Objekten Redis braucht.

Bei mir läuft eine Hauptinstanz von ioBroker auf meinem NAS und 4 weitere Raspberry PI sind im Haus verteilt und steuern Relais (via I2C) und die LED-Steuerung (via uDMX) an. Ich habe von Anfang an auf Redis gesetzt; das war scheinbar eine gute Entscheidung :-).

Ja, der Adapter wird noch weiter entwickelt. Im Moment bin ich am Aufarbeiten von den zahlreichen Pendenzen; neue Features erwarte ich ab Ende Februar einbauen zu können.
