### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [UncleSamSwiss/ioBroker.loxone#21]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/UncleSamSwiss/ioBroker.loxone

- [ ] [E106] Title should not have word "adapter" in the name. It is clear, that this is adapter. Now: Loxone Miniserver Adapter
- [ ] [E114] No adapter are allowed in the repo without admin3 support
- [ ] [E116] No SPDX license found. Please use one of listed here: https://spdx.org/licenses/
- [ ] [E117] Licenses in package.json and in io-package.json are different
- [ ] [E140] width and height of logo are not equal
- [ ] [E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.loxone"
- [ ] [E802] No topics found in the repository. Please go to "https://github.com/UncleSamSwiss/ioBroker.loxone" and press "Manage topics"
- [ ] [E604] No "## License" found in README.md

I have also found warnings that may be fixed if possible.

- [ ] [W113] Adapter should support compact mode

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by UncleSamSwiss** [comment]
All adapter checks are successful with versions 1.1.0 and 2.0.0.

Version 2.0.0 has proper support for materialize and Admin 3.
