### ISSUE TITLE
Adapter not connecting to Miniserver Go Gen.2 (like #46, #56)

### ISSUE THREAD

**Issue by gbyhtn** [UncleSamSwiss/ioBroker.loxone#210]
Hello,
freshly installed Loxone-Adapter on previously running iob.
Versions:
Adapter version: 2.2.3
JS-Controller version: 3.3.21
Node version: 14.18.1
Operating system: Debian on Proxmox
Loxone Miniserver Go Gen.2: 12.2.11.5

Same issue as reported earlier (#46/#56)
Status in iob-loxone-Instance: Orange (green-green-red)
Log shows error: 

`loxone.0`` | 2021-12-05 12:49:41.521 | error | Miniserver connection error: Error [ERR_STREAM_WRITE_AFTER_END]: write after end`

WorkAround from Issue #46 (How-To.txt) not working.
Started new Project in LoxConfig,  modified empty project with renamed admin (pw: only a-z), saved project into Miniserver. Reentered this User/PW in Adapter-Instance. Again no connection established.
Since it's a MS Go no further extension applied, only internal Airbase.
THX
Ralf

**Comment by tdesmet** [comment]
I have the same issue with a loxone miniserver gen 1. Just updated to the latest version.
iobroker is a new installation running on a ubuntu 20.04 server. 
I found this issue https://github.com/alladdin/node-lox-ws-api/issues/26 

So I think it is an issue with node-lox-ws-api. But there doesn't seem to be any active development there.


Any reason why this project is not using https://github.com/Loxone/lxcommunicator? It is a node library maintained by loxone to communicate with the miniserver...
I am going to look into porting ioBroker.loxone so it uses lxcommunicator and I am wondering if the maintainers are interested?
