### ISSUE TITLE
Fehler bei Update 2.2.3 auf 3.0.0

### ISSUE THREAD

**Issue by MatthiasBosch** [UncleSamSwiss/ioBroker.loxone#219]
Hallo,

das Update von Version 2.2.3 auf 3.0.0 funktioniert bei mir nicht.
ioBroker läuft auf einem Raspi
Nodejs ist auf 14.18.3
NPM ist 6.12

Folgende Ausgabe erhalte ich:
```
_$ iobroker upgrade loxone@3.0.0

Update loxone from @2.2.3 to @3.0.0

NPM version: 6.12.0

npm install iobroker.loxone@3.0.0 --loglevel error --prefix "/opt/iobroker" (System call)

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v83-linux-glibc-arm.tar.gz

Package pixman-1 was not found in the pkg-config search path.Perhaps you should add the directory containing `pixman-1.pc'to the PKG_CONFIG_PATH environment variableNo package 'pixman-1' foundgyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp

gyp ERR! configure error

gyp ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)gyp ERR! stack at ChildProcess.emit (events.js:400:28)gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)

gyp ERR! System Linux 5.10.63-v7l+gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/iobroker/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"gyp ERR! cwd /opt/iobroker/node_modules/canvasgyp ERR! node -v v14.18.3

gyp ERR! node-gyp -v v5.0.5gyp ERR! not ok

node-pre-gyp ERR! build error

node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/iobroker/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)node-pre-gyp ERR! stack at ChildProcess.<anonymous> (/opt/iobroker/node_modules/canvas/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)node-pre-gyp ERR! stack at ChildProcess.emit (events.js:400:28)node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:1058:16)node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)

node-pre-gyp ERR! System Linux 5.10.63-v7l+node-pre-gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"node-pre-gyp ERR! cwd /opt/iobroker/node_modules/canvasnode-pre-gyp ERR! node -v v14.18.3node-pre-gyp ERR! node-pre-gyp -v v1.0.8node-pre-gyp ERR! not ok

internal/fs/utils.js:811 throw new ERR_INVALID_ARG_TYPE(

^TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined at Object.writeFileSync (fs.js:1521:5) at /opt/iobroker/node_modules/lxcommunicator/browserify.js:16:8 at Readable.<anonymous> (/opt/iobroker/node_modules/lxcommunicator/browserify.js:31:9) at Readable.emit (events.js:400:28) at endReadableNT (/opt/iobroker/node_modules/read-only-stream/node_modules/readable-stream/lib/_stream_readable.js:1010:12) at processTicksAndRejections (internal/process/task_queues.js:82:21) { code: 'ERR_INVALID_ARG_TYPE'}

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! lxcommunicator@1.1.1 postinstall: `node ./browserify.js`

npm ERR! Exit status 1npm ERR! npm ERR! Failed at the lxcommunicator@1.1.1 postinstall script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR! /home/iobroker/.npm/_logs/2022-01-27T11_53_04_282Z-debug.log

host.raspberrypi Cannot install iobroker.loxone@3.0.0: 1

ERROR: Process exited with code 25_
```

Gibt's ne Idee woran das liegen kann?

Danke & Grüße

**Comment by UncleSamSwiss** [comment]
Ich habe ein Issue eröffnet bei der Library, die das Problem macht (siehe oben).

Bis auf weiteres musst du auf der Version 2.2.3 bleiben. Sobald ich eine Antwort auf mein Issue habe, werde ich hier weiter informieren.

**Comment by Datenkrake156** [comment]
Hallo,

muß mich anschließen, allerdings auf einem Windows-10-Rechner.
NPM 6.14.15, Node.js 14.18.1

nach einer 20-minütigen Endlosschleife habe ich abgebrochen, der Adapter blieb trotz aller Bemühungen rot. Aus Verzweiflung habe ich deinstalliert und wollte neu installieren, ohne Erfolg.
Im Log steht folgendes: 
[2022-01-27T16_50_58_154Z-debug.log](https://github.com/UncleSamSwiss/ioBroker.loxone/files/7952457/2022-01-27T16_50_58_154Z-debug.log)



Selbst ein Versuch, von Github die alte Version zu installieren, schlägt fehl. Gibt es da noch einen Trick?
Vielen Dank im voraus

**Comment by UncleSamSwiss** [comment]
@Datenkrake156 Ich glaube nicht, dass das dasselbe Problem ist. Insbesondere weil die Installation einer alten Version nicht mehr funktioniert. Ich befürchte, dein System ist irgendwie nicht mehr sauber. Bitte frag im Forum nach, da gibt es Leute, die dir mit Windows und Berechtigungen besser helfen können als ich.

**Comment by Datenkrake156** [comment]
Hallo,

danke für die schnelle Antwort! Habe jetzt den Rechner (IOB hat eine eigene NUC) heruntergefahren und neu gestartet. Von Github habe ich die 2.2.3-zip heruntergeladen und dann lokal ohne Probleme installiert. Der update-Versuch auf Version 3 schlug allerdings erneut fehl. Werde diese Version daher ignorieren. Ansonsten läuft IOB ohne Probleme.
Danke für Deinen Einsatz und der Deiner Kollegen. Habe mit IOB noch einiges vor, aber mehr als  diese Fehlerhinweise kann ich als reiner Anwender leider nicht beisteuern.
Alles Gute

Armin

**Comment by UncleSamSwiss** [comment]
@Datenkrake156 du kannst auch eine bestimmte Version von npm installieren: einfach als "Adresse" des Adapters in ioBroker "iobroker.loxone@2.2.3" eingeben. Oder auf der Kommandozeile.

**Comment by UncleSamSwiss** [comment]
@Datenkrake156 Nachtrag: hast du im Ernst nur für ioBroker einen NUC und hast dort Windows installiert? In diesem Fall würde ich mir gut überlegen auf ein Ubuntu Server zu wechseln, weil grundsätzlich hast du weniger Probleme (und mehr Performance) wenn du ioBroker unter einem schlanken Linux (ohne GUI!) laufen lässt.

**Comment by MatthiasBosch** [comment]
> Ich habe ein Issue eröffnet bei der Library, die das Problem macht (siehe oben).
> 
> Bis auf weiteres musst du auf der Version 2.2.3 bleiben. Sobald ich eine Antwort auf mein Issue habe, werde ich hier weiter informieren.

Hi UncleSamSwiss,

hast Du schon eine Info zu dem Problem von Loxone erhalten?

Danke & Grüße
Matthias

**Comment by UncleSamSwiss** [comment]
Nein, den Link zum Issue findest du auch oben: https://github.com/Loxone/lxcommunicator/issues/16

**Comment by Arcticon** [comment]
@MatthiasBosch ich habe es gerade mal getestet und festgestellt das der adapter nur mit node 18 funktioniert.
kannst du das mal austesten?

**Comment by Datenkrake156** [comment]
Hallo Samuel,

gebe gerne das gewünschte feed-back.

js-controller 5.0.19
Node.js v18.20.2
NPM 10.5.0
Loxone-Adapter 3.0.1

Nachdem Loxone den damaligen Fehler in seiner Software beseitigt
hatte, rennt der Adapter ohne Probleme. Störungen gibt es eigentlich
nur, wenn Vodaschreck mal wieder mit seinem Internet-Kabel nicht
zurechtkommt.

Vielen Dank für die laufende Pflege!

Viele Grüße

Armin Hagedorn

P.S. so nebenbei zu Deinem damaligen Hinweis

Nachdem der IOB unter Windows leider ständig abstürzte (aus nicht
erklärlichen Ursachen) habe ich Mitte des letzten Jahres Mate als
Unterbau installiert. Seitdem habe ich keinen Absturz mehr erlebt, muß
aber immer Anleitungen finden, die ich wie ein dressierter Affe
eintippen kann! Hat halt alles Vor- und Nachteile.



@MatthiasBosch ich habe es gerade mal getestet und festgestellt das der
adapter nur mit node 18 funktioniert.
kannst du das mal austesten?

**Comment by Arcticon** [comment]
@UncleSamSwiss @raintonr looks like we can close this issue :)

**Comment by raintonr** [comment]
Well... I don't speak German, so will take your word for it :wink:
