### ISSUE TITLE
Unsupported control type TextState

### ISSUE THREAD

**Issue by huschi83** [UncleSamSwiss/ioBroker.loxone#23]
Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined

{
  "from": "system.adapter.loxone.0",
  "ts": 1551539460601,
  "common": {
    "name": "TTS",
    "type": "string",
    "role": "text",
    "read": true,
    "write": false
  },
  "native": {
    "name": "TTS",
    "type": "InfoOnlyText",
    "uuidAction": "131e81a1-00ce-5d00-ffff403fb0c34b9e",
    "room": "0b734138-03ac-03f0-ffff403fb0c34b9e",
    "cat": "0b734138-035d-0300-ffff403fb0c34b9e",
    "defaultRating": 0,
    "isFavorite": false,
    "isSecured": false,
    "defaultIcon": null,
    "details": {
      "format": "%s"
    },
    "states": {
      "text": "131e81a1-00ce-5d00-ffff403fb0c34b9e"
    }
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "loxone.0.Unsupported.131e81a1-00ce-5d00-ffff403fb0c34b9e",
  "type": "state"
}

**Comment by patrick-dmxc** [comment]
I need this to

**Comment by EyesOnly1** [comment]
Hallo,

die Übernahme von Texten aus Loxone würde ich auch benötigen.

**Comment by grossfr** [comment]
Dies Übernahme von Texten von Loxone in iobroker wird dringendst benötigt.
Kennt jemand einen Workaround?

**Comment by UncleSamSwiss** [comment]
Released in 2.1.0

**Comment by EyesOnly1** [comment]
Hallo, Bekomme noch folgende Meldung bei den STatus Objekten:
Currently unsupported control type TextState: Error: Cannot find module './controls/TextState'

**Comment by grossfr** [comment]
Hallo,
ich bekomme ebenfalls mit der Version 2.1.0 folgende Fehlermeldungen:
(10375) Currently unsupported control type TextState: Error: Cannot find module './controls/TextState'
(10375) Currently unsupported control type Daytimer: Error: Cannot find module './controls/Daytimer'
(10375) Currently unsupported control type InfoOnlyText: Error: Cannot find module './controls/InfoOnlyText'
(10375) Currently unsupported control type Daytimer: Error: Cannot find module './controls/Daytimer'
(10375) Currently unsupported control type Hourcounter: Error: Cannot find module './controls/Hourcounter'
(10375) Currently unsupported control type Heatmixer: Error: Cannot find module './controls/Heatmixer'
(10375) Currently unsupported control type Radio: Error: Cannot find module './controls/Radio'
(10375) Currently unsupported control type Webpage: Error: Cannot find module './controls/Webpage'
