### ISSUE TITLE
Connection problems with new Miniserver Firmware (10.2.3.26)

### ISSUE THREAD

**Issue by scholzsebi** [UncleSamSwiss/ioBroker.loxone#25]
Hello,

since my Miniserver Firmware Update to Version 10.2.3.26 i have no connection between iO Broker and the Loxone Adapter. The status light in iO Broker flashes between green and yellow each second.

Kind regards

Sebastian

**Comment by UncleSamSwiss** [comment]
Problem has been solved by @scholzsebi by recreating the configuration from scratch:

> ich habe nun mit viel Arbeit meine Config-Datei neu aufgebaut, da ich den Fehler leider nicht finden konnte. Auch mit einem neuen Benutzer bekam ich keine Verbindung zwischen dem Loxone Adapter und dem Miniserver. Ich glaube die Config wurde durch das Upgrade von 10.0 auf 10.2 zerschossen. Denn genau danach haben die Probleme begonnen.
