### ISSUE TITLE
Unsupported control type: Remote

### ISSUE THREAD

**Issue by patrick-dmxc** [UncleSamSwiss/ioBroker.loxone#31]
{
  "from": "system.adapter.loxone.0",
  "user": "system.user.admin",
  "ts": 1561747918731,
  "common": {
    "name": "Fernbedienung für TV; PowerOn",
    "type": "string",
    "role": "text",
    "read": true,
    "write": false
  },
  "native": {
    "name": "Fernbedienung für TV; PowerOn",
    "type": "Remote",
    "uuidAction": "1185b365-028e-8a70-ffff4347a30666d9",
    "room": "1184afdc-01ed-0efe-ffffb696be9cf249",
    "cat": "1184afdc-00ce-0e43-ffffb696be9cf249",
    "defaultRating": 7,
    "isFavorite": true,
    "isSecured": false,
    "details": {
      "favoritePad": 0,
      "modeList": {
        "1": {
          "name": "TV",
          "favoritePad": 1,
          "usedButtons": [
            "power",
            "power",
            "mute",
            "volplus",
            "volminus",
            "prgplus",
            "prgminus",
            "btnred",
            "btngreen",
            "btnyellow",
            "btnblue",
            "dirup",
            "dirdown",
            "dirleft",
            "dirright",
            "dirok",
            "num0",
            "num1",
            "num2",
            "num3",
            "num4",
            "num5",
            "num6",
            "num7",
            "num8",
            "num9",
            "return",
            "menu",
            "guide",
            "info",
            "exit",
            "play",
            "pause",
            "stop",
            "next",
            "previous",
            "forward",
            "rewind"
          ]
        }
      }
    },
    "states": {
      "timeout": "1185b365-028e-8a52-ffffeb0e90f9dffe",
      "mode": "1185b365-028e-8a54-ffffeb0e90f9dffe",
      "active": "1185b365-028e-8a12-ffffeb0e90f9dffe"
    }
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "loxone.0.Unsupported.1185b365-028e-8a70-ffff4347a30666d9",
  "type": "state"
}

**Comment by UncleSamSwiss** [comment]
Thanks for the report of this new control.

Do you need this to be controllable by ioBroker? To me it seems this is a pure "input" device.
If you need it, I will of course implement it; if it's only the error message that is bothering you, I won't implement it.

**Comment by UncleSamSwiss** [comment]
No answer from reporter, closing.

**Comment by raintonr** [comment]
Few basic functions added with #350.
