### ISSUE TITLE
Weather Service

### ISSUE THREAD

**Issue by EyesOnly1** [UncleSamSwiss/ioBroker.loxone#32]
Hallo,

das Thema IO Broker ist für mich ganz neu, beschäftige mich jetzt seit 3 Tagen mit dem Thema. Nun habe ich bereits die ersten Verbindungen von Loxone zu Hue und Homematic erfolgreich einrichten und für mich anpassen können. 
Leider habe ich bei den Weather Service noch Probleme. Habe die Wetterdaten von wunderground im Broker, bekomme diese aber nicht in Loxone. Gibt was Mache ich falsch? Der Wert wird im Datenpunkt eingetragen. Loxone bekommt aber nichts.
![weather service](https://user-images.githubusercontent.com/34064550/61111808-b6c02a80-a48a-11e9-8d3f-f012b61d1cd8.JPG)

LG
EyesOnly1

**Comment by UncleSamSwiss** [comment]
Leider kann der Adapter nur die Wetterdaten von Loxone in den ioBroker übernehmen und nicht umgekehrt (die einzelnen Werte wären eigentlich "read-only" in ioBroker).

Falls du einfach die Werte irgendwo im Loxone GUI darstellen willst, dann kannst du z.B. via JavaScript Adapter (oder node-red, ...) die Daten auf einen "Input" von Loxone legen.

Falls du den Wetterservice von Loxone durch wunderground ersetzen willst (Wetterabhängige Steuerung im Miniserver), dann wird das leider nicht gehen; dafür musst du den Service von Loxone benutzen:
z.B.: https://shop.loxone.com/dech/wetter-service-10-jahre.html
