### ISSUE TITLE
Couldn't enable status updates

### ISSUE THREAD

**Issue by oRudi07** [UncleSamSwiss/ioBroker.loxone#370]
Couldn't enable status updates: Diese Meldung kommt sehr oft in letzter Zeit.
Woran kann das liegen?
Adapter Version ist aktuell
Miniserver Version 2

**Comment by raintonr** [comment]
Please post some examples of this message from you log file.

Also, please try running with debug enabled and see if this shows any more clues as to what might be going wrong.
