### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by josefglatz** [UncleSamSwiss/ioBroker.loxone#398]
Actual Loxone Config (internal) Alpha doesn't work with this plugin anymore. Have to dig deeper.

Do you have plans to maintain this repo in future?

**Comment by raintonr** [comment]
Yes, we absolutely need to keep this working.

What version of Loxone Config breaks this adapter? Do you have a link to the release notes?

**Comment by raintonr** [comment]
Yes. Am on Loxone Config 14.x here and works fine. So will close this.
