### ISSUE TITLE
Miniserver Gen. 2 won't connect

### ISSUE THREAD

**Issue by COMHOME** [UncleSamSwiss/ioBroker.loxone#40]
I got the new version of the miniserver here and can't connect. What can i do to help integrating v2 miniserver with https?

**Comment by COMHOME** [comment]
Is this project still alive?

**Comment by manuelmaudrich** [comment]
Leider funktioniert der Loxone Adapter im ioBroker für den Loxone Miniserver V2 nicht mehr. Möglicherweise liegt es am HTTPS Request welches bis lang im V1 nur unter HTTP lief. Ist es möglich den aktuellen Adapter dahingehend anzupassen bzw. einen neuen Adapter zu entablieren?

Grüße im Namen der Loxone- und Allroundbastler- Community

**Comment by Apollon77** [comment]
Ich denke es liegt auch an der verwendeten Library ... die geht hier nur auf ws ... also nicht wss ...

https://github.com/alladdin/node-lox-ws-api/blob/master/lib/Connection.js#L35

Wer mal expterimentieren will könnte überlegen ob er mal diese library in seinen node_modules sucht und dort an der sstelle ein "wss" reinschreibt. Wenn es dann mgisch tut kann man mal schauen das man es bei der Library einkippt

**Comment by COMHOME** [comment]
Ich stelle auch gerne v2 Test-Hardware zur Verfügung. Wäre schön, wenn UncleSamSwiss sich mal dazu melden würde...

**Comment by Apollon77** [comment]
Experimentiert doch mal mit dem oben genannten :-)

**Comment by COMHOME** [comment]
> Experimentiert doch mal mit dem oben genannten :-)

Sind wir dran, Termin für morgen steht schon! 😉

**Comment by COMHOME** [comment]
<img width="819" alt="Bildschirmfoto 2020-02-20 um 13 30 56" src="https://user-images.githubusercontent.com/24495786/74933995-8576e800-53e5-11ea-84d5-530d2feba4db.png">
WSS einfach eintragen scheint auch nicht die Lösung zu sein...
Hat sonst jemand einen Ansatz?

**Comment by Pherekles** [comment]
Hi folks - the latest version of 'node-lox-ws-api' provided by npm is not up 2 date. The ioBroker library for Loxone refers to it as you can see in the following pic.

![1](https://user-images.githubusercontent.com/47866553/74938839-0dadbb00-53ef-11ea-990e-06e6a0066bec.JPG)
URL: https://github.com/UncleSamSwiss/ioBroker.loxone/blob/master/package.json


Here you can see that there where no updates in the last time.

![2](https://user-images.githubusercontent.com/47866553/74939018-6ed58e80-53ef-11ea-8e5d-0a0731a92d6e.JPG)
URL: https://www.npmjs.com/package/node-lox-ws-api

When you change your code directly like madito & alladdin already did on the 5th january the issue will be solved.

URL: https://github.com/alladdin/node-lox-ws-api/commit/624339fd71fcb53895eb8c0800d545319d8e6e97

**Comment by Apollon77** [comment]
@COMHOME does that work? Then we could simpy use this github repo as dependency ...

**Comment by COMHOME** [comment]
Yep, it‘s working!

**Comment by Apollon77** [comment]
First question is if we get Sklavin to release an official npm version ;-)

**Comment by UncleSamSwiss** [comment]
Big sorry guys, but now I'm back :-).

As I can see, the new node-lox-ws-api was released, so I'll test and integrate it ASAP.
