### ISSUE TITLE
Stairwell Light Switch needs active object that reflects block output

### ISSUE THREAD

**Issue by raintonr** [UncleSamSwiss/ioBroker.loxone#41]
Regarding the 'Stairwell Light Switch' block in Loxone:

https://www.loxone.com/enen/kb/stairwell-light-switch/

In the ioBroker adapter it currently has the following objects:

- 'active'. A button that turns the output 'Q' on in Loxone indefinitely.
- 'deactivationDelay'. A variable showing the number of seconds left to run on the timer.
- 'deactivationDelayTotal'. A variable showing the configured timer duration.
- 'pulse'. A button that activates (or restarts if already running) the timer.

The following two objects should also be included:

- An active state to reflect the output 'Q' in Loxone. Without this it is difficult to determine if the output is actually on or not (one can check for deactivationDelay != 0 but that is not nice).
- A reset button that should stop any running timer which is the equivalent of the 'R' input in Loxone.

IMHO the current 'active' object should be renamed 'on' or 'turnOn' or similar. The a new object can take the 'active' name that reflects if the output 'Q' in Loxone is actually on or not. Finally a 'reset' object button should be added.

**Comment by UncleSamSwiss** [comment]
Unfortunately Loxone doesn't provide `Q` in the web protocol. You will need to check `deactivationDelay` as you explained.

In version 2.0.2 the "active" object was replaced by two separate "on" and "off" objects which actually do what you expect them to do (turn permanently on or off).
