### ISSUE TITLE
Not able to install Loxone adapter in the new version of  IoBroker v6.3.5 on Raspberry P iOs

### ISSUE THREAD

**Issue by Sliderem** [UncleSamSwiss/ioBroker.loxone#417]
**Describe the bug**  
Not able to install Loxone adapter in the new version of  IoBroker v.6.3.5 on Raspberry Pi 4 

**To Reproduce**  
Install the  IoBroker on Raspberry Pi OS
Try to install  the e Loxone Adapter
Error prompted:

host.raspberrypi 2023-04-10 14:57:37.528 info iobroker exit 25
host.raspberrypi 2023-04-10 14:57:36.454 error iobroker host.raspberrypi Cannot install iobroker.loxone@3.0.1: 1
host.raspberrypi 2023-04-10 14:56:41.380 info iobroker Installing iobroker.loxone@3.0.1... (System call)
host.raspberrypi 2023-04-10 14:56:41.377 info iobroker NPM version: 8.19.3
host.raspberrypi 2023-04-10 14:56:34.358 info iobroker add loxone --host raspberrypi
 ​

**Expected behavior**  
have the Loxone Adapter installed in IoBroker

**Versions:**  

Platform: linux operating system: linux Architecture: arm CPUs: 4 Speed: 1100 MHz Model: unknown RAM: 3.7 GB System uptime: 05:29:08 Node.js: v16.19.1 time: 1681243266009 timeOffset: -60 adapters count: 471 NPM: 8.19.3 Disk size: 117.2 GB Disk free: 104.1 GB Uptime: 05:29:09 Active instances: 5 Path: /opt/iobroker/ alive:

**Comment by raintonr** [comment]
Nothing to do with RPi4 as am running on one here.

We need to see more from the log file please.

**Comment by Sliderem** [comment]
Thanks for the quick response!

What logs should I provide?


I have this logs from ioBroker interface, but I see there are not enough :


host.raspberrypi 2023-04-10 14:57:37.528 info iobroker exit 25
host.raspberrypi 2023-04-10 14:57:36.454 error iobroker host.raspberrypi Cannot install iobroker.loxone@3.0.1: 1
host.raspberrypi 2023-04-10 14:56:41.380 info iobroker Installing iobroker.loxone@3.0.1... (System call)
host.raspberrypi 2023-04-10 14:56:41.377 info iobroker NPM version: 8.19.3
host.raspberrypi 2023-04-10 14:56:34.358 info iobroker add loxone --host raspberrypi%0
​

**Comment by Sliderem** [comment]
Thanks for the quick response!

What logs should I provide?


I have this logs from ioBroker interface, but I see there are not enough :


host.raspberrypi 2023-04-10 14:57:37.528 info iobroker exit 25
host.raspberrypi 2023-04-10 14:57:36.454 error iobroker host.raspberrypi Cannot install iobroker.loxone@3.0.1: 1
host.raspberrypi 2023-04-10 14:56:41.380 info iobroker Installing iobroker.loxone@3.0.1... (System call)
host.raspberrypi 2023-04-10 14:56:41.377 info iobroker NPM version: 8.19.3
host.raspberrypi 2023-04-10 14:56:34.358 info iobroker add loxone --host raspberrypi%0
​

**Comment by raintonr** [comment]
You can look in `/opt/iobroker/log/iobroker.current.log` or alternately, install the package directly from the command line:

```
cd /opt/iobroker/
npm i iobroker.loxone
```

**Comment by raintonr** [comment]
No worries then. Closing.
