### ISSUE TITLE
Schalter ist nicht umschaltbar

### ISSUE THREAD

**Issue by GermanSheepDog** [UncleSamSwiss/ioBroker.loxone#429]
Eine Schalter in der Loxone-App zum Einschalten einer Wallbox soll vom iobroker aus eingeschaltet werden, um die Steuerung für eine Solaranlage zu übernehmen.

Der Loxone-Schalter ist in iobroker sichtbar und jeder Umschaltvorgang über die Loxone-App ist über "loxone.0.<id>.active" erkennbar. Ein NodeRed-Schalter kann im iobroker den Eintrag "loxone.0.<id>.active" aktualisieren, ABER in Loxone kommt nichts an:
- Der Schalter bewegt sich nicht.
- Es wird keine Loxone-Ereignis an die Wallbox gesendet, d.h. der Schalter liefert keinen Output.

**Versions:**  
 - Loxone-Adapter version: 3.01
 - Node version: 4.00

**Comment by raintonr** [comment]
What happens if you set the state directly from the IoB admin objects page? Does the switch update in Loxone?

**Comment by GermanSheepDog** [comment]
@raintonr : If I change the switch state directly from the IoB admin objects page, the state at the object state changed to the new value, BUT on Loxone nothing happened.
The object IoB-attributes are:
´´´
{
  "type": "state",
  "common": {
    "name": "Wallbox On: active",
    "read": true,
    "write": true,
    "type": "boolean",
    "role": "switch"
  },
  "native": {
    "uuid": "<id>"
  },
  "from": "system.adapter.loxone.0",
  "user": "system.user.admin",
  "ts": 1684056204774,
  "_id": "loxone.0.<id>.active",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
´´´

**Comment by raintonr** [comment]
I suspect a permission problem with your Loxone block. Login to the Loxone Web UI using the credentials configured in your IoB Loxone adapter... can you see this switch and change it's value?

Also try this: stop the Loxone adapter, delete the object (and children): `loxone.0.<id>`, restart Loxone adapter. This object and children should be recreated. Check again if changing it in IoB causes the change to be sent to Loxone.

**Comment by GermanSheepDog** [comment]
@raintonr I got a problem with the Loxone object! I stop the Loxone adapter, delete the object and their two childrens and restart Loxone adapter. All worked fine.
GREAT THANK
