### ISSUE TITLE
Light control with type lumitech

### ISSUE THREAD

**Issue by marvincaspar** [UncleSamSwiss/ioBroker.loxone#44]
If I have a light with type lumitech it is not available in ioBroker

**Comment by UncleSamSwiss** [comment]
Can you please provide more information?
Please follow https://github.com/UncleSamSwiss/ioBroker.loxone#bug-reports-and-feature-requests

I need the exact error message and the native value.

**Comment by EyesOnly1** [comment]
here is my configuration:
Currently unsupported sub-control type ColorPickerV2: Unsup{
  "from": "system.adapter.loxone.0",
  "user": "system.user.admin",
  "ts": 1609920897642,
  "common": {
    "name": "Esszimmer Lichtsteuerung",
    "role": "light",
    "smartName": {
      "de": "Licht Esszimmer"
    }
  },
  "native": {
    "control": {
      "name": "Esszimmer Lichtsteuerung",
      "type": "LightControllerV2",
      "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e",
      "room": "0b734138-038c-03aa-ffff403fb0c34b9e",
      "cat": "0b734138-033e-02d4-ffff403fb0c34b9e",
      "defaultRating": 0,
      "isFavorite": false,
      "isSecured": false,
      "details": {
        "movementScene": 1,
        "masterValue": "12de2c76-02f2-74b6-ffff403fb0c34b9e/masterValue",
        "masterColor": "12de2c76-02f2-74b6-ffff403fb0c34b9e/masterColor"
      },
      "states": {
        "activeMoods": "12de2c76-02f2-746e-ffffa785f8e6fa19",
        "moodList": "12de2c76-02f2-746f-ffffa785f8e6fa19",
        "favoriteMoods": "12de2c76-02f2-7470-ffffa785f8e6fa19",
        "additionalMoods": "12de2c76-02f2-7471-ffffa785f8e6fa19"
      },
      "subControls": {
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/masterValue": {
          "name": "Master-Helligkeit",
          "type": "Dimmer",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/masterValue",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "states": {
            "position": "12de2c76-02f2-74b2-ffffa785f8e6fa19",
            "min": "12de2c76-02f2-7473-ffffa785f8e6fa19",
            "max": "12de2c76-02f2-7474-ffffa785f8e6fa19",
            "step": "12de2c76-02f2-748e-ffffa785f8e6fa19"
          }
        },
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/masterColor": {
          "name": "Master-Farbe",
          "type": "ColorPickerV2",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/masterColor",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "details": {
            "pickerType": "Rgb"
          },
          "states": {
            "color": "12de2c76-02f2-74b1-ffffa785f8e6fa19",
            "sequence": "12de2e07-0034-c602-ffff403fb0c34b9e",
            "sequenceColorIdx": "12de2e07-0034-c603-ffff403fb0c34b9e"
          }
        },
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI1": {
          "name": "Alle Lampen",
          "type": "ColorPickerV2",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI1",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "details": {
            "pickerType": "Lumitech"
          },
          "states": {
            "color": "12de2c76-02f2-749f-ffffa785f8e6fa19",
            "sequence": "12de2e07-0034-c5de-ffff403fb0c34b9e",
            "sequenceColorIdx": "12de2e07-0034-c5df-ffff403fb0c34b9e"
          }
        },
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI2": {
          "name": "Spot 1",
          "type": "ColorPickerV2",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI2",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "details": {
            "pickerType": "Lumitech"
          },
          "states": {
            "color": "12de2c76-02f2-74a0-ffffa785f8e6fa19",
            "sequence": "12de2e07-0034-c5e0-ffff403fb0c34b9e",
            "sequenceColorIdx": "12de2e07-0034-c5e1-ffff403fb0c34b9e"
          }
        },
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI3": {
          "name": "Spot 2",
          "type": "ColorPickerV2",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI3",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "details": {
            "pickerType": "Lumitech"
          },
          "states": {
            "color": "12de2c76-02f2-74a1-ffffa785f8e6fa19",
            "sequence": "12de2e07-0034-c5e2-ffff403fb0c34b9e",
            "sequenceColorIdx": "12de2e07-0034-c5e3-ffff403fb0c34b9e"
          }
        },
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI4": {
          "name": "Spot 3",
          "type": "ColorPickerV2",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI4",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "details": {
            "pickerType": "Lumitech"
          },
          "states": {
            "color": "12de2c76-02f2-74a2-ffffa785f8e6fa19",
            "sequence": "12de2e07-0034-c5e4-ffff403fb0c34b9e",
            "sequenceColorIdx": "12de2e07-0034-c5e5-ffff403fb0c34b9e"
          }
        },
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI5": {
          "name": "Spot 4",
          "type": "ColorPickerV2",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI5",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "details": {
            "pickerType": "Lumitech"
          },
          "states": {
            "color": "12de2c76-02f2-74a3-ffffa785f8e6fa19",
            "sequence": "12de2e07-0034-c5e6-ffff403fb0c34b9e",
            "sequenceColorIdx": "12de2e07-0034-c5e7-ffff403fb0c34b9e"
          }
        },
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI6": {
          "name": "Spot 5",
          "type": "ColorPickerV2",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI6",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "details": {
            "pickerType": "Lumitech"
          },
          "states": {
            "color": "12de2c76-02f2-74a4-ffffa785f8e6fa19",
            "sequence": "12de2e07-0034-c5e8-ffff403fb0c34b9e",
            "sequenceColorIdx": "12de2e07-0034-c5e9-ffff403fb0c34b9e"
          }
        },
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI7": {
          "name": "Spot 6",
          "type": "ColorPickerV2",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI7",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "details": {
            "pickerType": "Lumitech"
          },
          "states": {
            "color": "12de2c76-02f2-74a5-ffffa785f8e6fa19",
            "sequence": "12de2e07-0034-c5ea-ffff403fb0c34b9e",
            "sequenceColorIdx": "12de2e07-0034-c5eb-ffff403fb0c34b9e"
          }
        },
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI8": {
          "name": "Spot 7",
          "type": "ColorPickerV2",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI8",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "details": {
            "pickerType": "Lumitech"
          },
          "states": {
            "color": "12de2c76-02f2-74a6-ffffa785f8e6fa19",
            "sequence": "12de2e07-0034-c5ec-ffff403fb0c34b9e",
            "sequenceColorIdx": "12de2e07-0034-c5ed-ffff403fb0c34b9e"
          }
        },
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI9": {
          "name": "Spot 8",
          "type": "ColorPickerV2",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI9",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "details": {
            "pickerType": "Lumitech"
          },
          "states": {
            "color": "12de2c76-02f2-74a7-ffffa785f8e6fa19",
            "sequence": "12de2e07-0034-c5ee-ffff403fb0c34b9e",
            "sequenceColorIdx": "12de2e07-0034-c5ef-ffff403fb0c34b9e"
          }
        },
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI10": {
          "name": "Spot 9",
          "type": "ColorPickerV2",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI10",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "details": {
            "pickerType": "Lumitech"
          },
          "states": {
            "color": "12de2c76-02f2-74a8-ffffa785f8e6fa19",
            "sequence": "12de2e07-0034-c5f0-ffff403fb0c34b9e",
            "sequenceColorIdx": "12de2e07-0034-c5f1-ffff403fb0c34b9e"
          }
        },
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI11": {
          "name": "Spot 10",
          "type": "ColorPickerV2",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI11",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "details": {
            "pickerType": "Lumitech"
          },
          "states": {
            "color": "12de2c76-02f2-74a9-ffffa785f8e6fa19",
            "sequence": "12de2e07-0034-c5f2-ffff403fb0c34b9e",
            "sequenceColorIdx": "12de2e07-0034-c5f3-ffff403fb0c34b9e"
          }
        },
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI12": {
          "name": "Spot 11",
          "type": "ColorPickerV2",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI12",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "details": {
            "pickerType": "Lumitech"
          },
          "states": {
            "color": "12de2c76-02f2-74aa-ffffa785f8e6fa19",
            "sequence": "12de2e07-0034-c5f4-ffff403fb0c34b9e",
            "sequenceColorIdx": "12de2e07-0034-c5f5-ffff403fb0c34b9e"
          }
        },
        "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI13": {
          "name": "Spot 12",
          "type": "ColorPickerV2",
          "uuidAction": "12de2c76-02f2-74b6-ffff403fb0c34b9e/AI13",
          "defaultRating": 0,
          "isFavorite": false,
          "isSecured": false,
          "details": {
            "pickerType": "Lumitech"
          },
          "states": {
            "color": "12de2c76-02f2-74ab-ffffa785f8e6fa19",
            "sequence": "12de2e07-0034-c5f6-ffff403fb0c34b9e",
            "sequenceColorIdx": "12de2e07-0034-c5f7-ffff403fb0c34b9e"
          }
        }
      }
    }
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "_id": "loxone.0.12de2c76-02f2-74b6-ffff403fb0c34b9e",
  "type": "device"
}ported color picker type: Lumitech
