### ISSUE TITLE
Unsupported Datenpunkte nach Update auf V2.0.0

### ISSUE THREAD

**Issue by MBeeken73** [UncleSamSwiss/ioBroker.loxone#47]
Hallo,
seit dem letzten Update (von 1.1.0 nach 2.0.0) werden virtuelle Datenpunkte aus Loxone als Unsupported deklariert.
Dementsprechend funktionieren diese auch nicht. Wenn ein Downgrade nach V1.1.0 gemacht wird funktioniert alles wieder.
Hat sich hier vielleicht ein Fehler eingeschlichen?

Log:
![Unbenannt](https://user-images.githubusercontent.com/48216471/90561393-f2a2e480-e1a0-11ea-9075-7e1a5ba2ecd8.jpg)

**Comment by UncleSamSwiss** [comment]
Sicherlich ein Fehler meinerseits. Was sind "virtuelle Datenpunkte?" (Sorry, ich verwende nur sehr wenige Features des Miniservers.)

Kannst du noch einen Screenshot der Objekte machen (insbesondere der erwähnten States) und das "native" eines der Devices als Kommentar hier hinschreiben (z.B. von loxone.0.155594db-00a460f4-ffffcbb38366f706).

**Comment by MBeeken73** [comment]
Ich habe ein Beispiel der Virtuellen Eingänge als Screenshot gemacht (Digital und Analog)

![Digital](https://user-images.githubusercontent.com/48216471/90788005-9b6a5480-e305-11ea-8941-ade0bb51fb97.JPG)
![Analog](https://user-images.githubusercontent.com/48216471/90788019-9f967200-e305-11ea-93ad-91644ff8e94a.JPG)

**Comment by MBeeken73** [comment]
> Sicherlich ein Fehler meinerseits. Was sind "virtuelle Datenpunkte?" (Sorry, ich verwende nur sehr wenige Features des Miniservers.)
> 
> Kannst du noch einen Screenshot der Objekte machen (insbesondere der erwähnten States) und das "native" eines der Devices als Kommentar hier hinschreiben (z.B. von loxone.0.155594db-00a460f4-ffffcbb38366f706).

Konntest du schon etwas feststellen?

**Comment by UncleSamSwiss** [comment]
Nachdem ich im Code nichts finden konnte, habe ich das nun auf einem echten Miniserver getestet und kann das irgendwie nicht reproduzieren:
- Ich habe die Virtuellen Eingänge in Loxone Config 11.0 erstellt (ein digitaler, ein analoger)
- ich habe sie einer "Seite" zugewiesen (sonst tauchen sie gar nicht auf)
- ich kann die Werte im Web-GUI wie auch in ioBroker.admin verstellen und sie werden gegenseitig aktualisiert.

Kannst du mir bitte noch die gewünschten Screenshots von ioBroker.admin geben, vielleicht finde ich noch etwas:

> Kannst du noch einen Screenshot der Objekte machen (insbesondere der erwähnten States) und das "native" eines der Devices als Kommentar hier hinschreiben (z.B. von loxone.0.155594db-00a460f4-ffffcbb38366f706).

Wie du an diese Infos kommst, findest du hier: https://github.com/UncleSamSwiss/ioBroker.loxone#bug-reports-and-feature-requests

**Eine Möglichkeit sehe ich noch:**
Funktioniert die Verbindung von ioBroker zum Miniserver überhaupt? Ist Die Verbindungsanzeige in ioBroker grün? Kannst du das Log vom Aufstarten des Adapters auch noch hier posten?

**Comment by MBeeken73** [comment]
Danke für dein Antwort!
Die Unsupported Datenpunkte sind bei mir jetzt auch nicht mehr vorhanden. Warum auch immer.
Beim Testen des analogen virtuellen Datenpunktes ist mir aber aufgefallen das wenn ich z.B den Wert von 1 nach 0 ändere 
dieser nicht übertragen wird (Senderichtung ioBroker nach Loxone).
Andersrum funktioniert es!
Die "0" scheint er nicht zu nehmen.

Ist das bei dir auch zu reproduzieren?

Vielen Dank für deine Hilfe!
