### ISSUE TITLE
Farblicht: level.color.[blue|red|green] setzen funktioniert in v2.0.1 nicht mehr

### ISSUE THREAD

**Issue by rrov1** [UncleSamSwiss/ioBroker.loxone#52]
Hallo,

ich habe den Adapter in der 2.0.1 im Einsatz und mir ist eben aufgefallen, dass bei einem Farblicht das setzen der RGB-Werte nicht mehr funktioniert (im Adapter v1.1.0 wird der entsprechende Farbwert aktiviert).

**To Reproduce**  
1. Im Object Browser ein Farblicht heraussuche, z.B. Rolle 'level.color.blue'.
2. Einen Farbwert zw. 1 und 255 setzen.
3. Der Farbwert wird nicht umgesetzt.

**Expected behavior**  
Der Farbwert müsste durch das Loxone Farblicht umgesetzt werden.

**Versions:**  
 - Adapter version: 2.0.1

Vielleicht lässt sich der Fehler ja beheben.

Danke.

**Comment by tom1104** [comment]
Hallo,
ich bin nicht sicher, ob mein problem das gleiche ist aber auch ich habe Probleme mit den RGB.

ich habe wie oben beschrieben die v1.1.0 installiert und da funktioniert es. 
in v2.0.2 habe ich das Phänomen, dass der zu schreibende Wert nach dem schreiben durch 10 geteilt wird. also aus 255 wird 26. 2550 wird dadurch zu 255.

Ein weiteres "Problem" ist, dass die verfügbaren ColorPicker widgets über den RGB "Ausgang" nicht 0,0,0 sondern #000000 ausgibt. Wird an sich aber nicht benötigt.

Grüße
Tom
