### ISSUE TITLE
Loxone (partly) not connected, instance statusyellow / Loxone verbindungsprobleme (Loxone > iobroker, Outputs)

### ISSUE THREAD

**Issue by wokka121162** [UncleSamSwiss/ioBroker.loxone#54]
Loxone (partly) not connected, instance statusyellow / Loxone Verbindungsprobleme (Loxone > iobroker, Outputs)

Problem:
Statusänderung in Loxone (z.B. Virtual Output or 2-Button-switch) > keine Stautsänderung in ioBroker.
d.h. Signale von Loxone > ioBroker nicht möglich
Unerwarteter Ausfall nach ca. 1-monatigem problemlosen Betrieb

Statusanzeige Adapter:
Verbunden mit Host: wahr
Lenenszeichen: wahr
Verbunden mit Loxone: falsch
Remark: signals from ioBroker to Loxone ok!   e.g. > Virtual Loxone Input...

>> d.h.: ioBroker ist derzeit nicht nutzbar für mich, möglicher Zeitpunkt seit Fehler: 
Loxone Update von ca. 11.2.10.8 auf 11.2.10.19 (bin mir aber nicht sicher)
Firmware: 11.2.10.19
Config:  11.2.10.19
Nodejs 10.20.1

Log-Auszug:

host.raspberrypi-1 | 2020-10-25 18:25:00.036 | info | instance system.adapter.daswetter.0 started with pid 4541
-- | -- | -- | --
javascript.1 | 2020-10-25 18:24:59.050 | info | (1314) Stop script script.js.Test.VQ1-Test
javascript.0 | 2020-10-25 18:24:59.043 | info | (1202) Stop script script.js.Test.VQ1-Test
loxone.0 | 2020-10-25 18:21:54.343 | error | (1753) Couldn't load structure file: Error: The  "enum.functions.Beschattung-Einstellung allg." is invalid. Ids are not  allowed to end in "."
loxone.0 | 2020-10-25 18:21:53.792 | error | (1753) Unsupported control type Radio: Error: Cannot find module './controls/Radio'
loxone.0 | 2020-10-25 18:21:52.758 | error | (1753) Unsupported control type TextState: Error: Cannot find module './controls/TextState'
loxone.0 | 2020-10-25 18:21:51.347 | error | (1753) Unsupported control type TextState: Error: Cannot find module './controls/TextState'
loxone.0 | 2020-10-25 18:21:51.298 | error | (1753) Unsupported control type TextState: Error: Cannot find module './controls/TextState'
loxone.0 | 2020-10-25 18:21:51.244 | error | (1753) Unsupported control type TextState: Error: Cannot find module './controls/TextState'
loxone.0 | 2020-10-25 18:21:51.238 | error | (1753) Unsupported control type TextState: Error: Cannot find module './controls/TextState'
loxone.0 | 2020-10-25 18:21:38.549 | error | (1753) Unsupported control type Daytimer: Error: Cannot find module './controls/Daytimer'
loxone.0 | 2020-10-25 18:21:34.698 | error | (1753) Unsupported control type SystemScheme: Error: Cannot find module './controls/SystemScheme'
loxone.0 | 2020-10-25 18:21:34.438 | error | (1753) Unsupported control type Presence: Error: Cannot find module './controls/Presence'
loxone.0 | 2020-10-25 18:21:32.647 | error | (1753) Unsupported control type Daytimer: Error: Cannot find module './controls/Daytimer'
loxone.0 | 2020-10-25 18:21:32.597 | error | (1753) Unsupported control type TextState: Error: Cannot find module './controls/TextState'
loxone.0 | 2020-10-25 18:21:29.719 | error | (1753) Unsupported control type Daytimer: Error: Cannot find module './controls/Daytimer'
loxone.0 | 2020-10-25 18:21:23.206 | error | (1753) Unsupported control type TextState: Error: Cannot find module './controls/TextState'
loxone.0 | 2020-10-25 18:21:23.197 | error | (1753) Unsupported control type TextState: Error: Cannot find module './controls/TextState'
loxone.0 | 2020-10-25 18:21:23.186 | error | (1753) Unsupported control type Daytimer: Error: Cannot find module './controls/Daytimer'
loxone.0 | 2020-10-25 18:21:23.175 | error | (1753) Unsupported control type Radio: Error: Cannot find module './controls/Radio'
loxone.0 | 2020-10-25 18:21:17.451 | error | (1753) Unsupported control type Presence: Error: Cannot find module './controls/Presence'
loxone.0 | 2020-10-25 18:21:17.350 | error | (1753) Unsupported control type NfcCodeTouch: Error: Cannot find module './controls/NfcCodeTouch'
loxone.0 | 2020-10-25 18:21:13.395 | info | (1753) got structure file; last modified on 2020-10-25 18:20:08
loxone.0 | 2020-10-25 18:21:11.856 | info | (1753) Miniserver connected

**Expected behavior**  
communicatio without problems, green loxone status for loxone adapter

**Versions:**  
 - Adapter version: <adapter-version> 2.01
- Loxone:
          Firmware: 11.2.10.19
           Config:  11.2.10.19

 - JS-Controller version: 3.1.5
 - Node version: 10.20.1
 - Operating system: ?

**Additional context**  

br
wokka@gmx.at

**Comment by UncleSamSwiss** [comment]
The problem is the function "Beschattung-Einstellung allg."

Currently it is not possible to have functions with a dot inside. You might want to change it to "Beschattung-Einstellung allgemein".

**Comment by wokka121162** [comment]
> 
> 
> The problem is the function "Beschattung-Einstellung allg."
> 
> Currently it is not possible to have functions with a dot inside. You might want to change it to "Beschattung-Einstellung allgemein".

Wow, perfect - now it's working! I remove the dot in  "Beschattung-Einstellung allg." 👍 👍 👍 👍 THX a lot !!!
