### ISSUE TITLE
Support for temperature sensor in Touch Tree devices

### ISSUE THREAD

**Issue by p-vitt** [UncleSamSwiss/ioBroker.loxone#55]
The humidity sensor from Touch Tree devices is supported, however, the temperature sensor from the same devices is not. There is also no error in the logs complaining about any unsupported types, so I can't provide any information about it. But as the humidity from those sensors is available, I hope that the temperature can be made available as well.
Thanks in advance!

Regards, Peter

**Comment by UncleSamSwiss** [comment]
I'm not sure why you don't see the temperature. I myself have 16 Touch Tree (and 4 Touch Air) and all of them report their temperature. Here one example:
![image](https://user-images.githubusercontent.com/7595126/99812982-66a9ab80-2b47-11eb-864d-f15695a1c42b.png)

Can you provide some more infos about your system? Version of Loxone, Firmware Version of Touch Tree, ...?

**Comment by p-vitt** [comment]
Shame on me. I forgot to check the Visualization box in Loxone Config. Sorry for asking...

**Comment by UncleSamSwiss** [comment]
No worries, thanks for the clarification.
