### ISSUE TITLE
Keine Änderungen an Loxone Werten vom Typ "virtuelle Eingänge" nach Loxone Update auf Version 15.0.5.11 mehr möglich

### ISSUE THREAD

**Issue by MatthiasBosch** [UncleSamSwiss/ioBroker.loxone#553]
Hallo zusammen,

ich habe gestern das neue Loxone Update auf die Version 15.0.5.15 gemacht.
Der Loxone Adapter hat die Version 3.0.1.

Danach kann ich im ioBroker keine Werte mehr ändern, die vom Typ "virtuelle Eingänge" sind.
Andere Typen sind meiner Ansicht nach nicht betroffen.
Sonst gab es zum Zustand, bei den es noch funktioniert hat keine Änderungen.

Kann das jemand auch nachvollziehen?

**Comment by raintonr** [comment]
Please look in your log file for errors. If there are none, please turn debug on and try to change your VI and see what the log says.

**Comment by MatthiasBosch** [comment]
There is a error message in the log: Unsupported state change: loxone.0.16a031ee-01a3-9c07-ffff403fb0c34b9e.value

**Comment by MatthiasBosch** [comment]
analog.
yesterday befor the Loxone Update to version 15.0.5.11 it worked. And I had no other changes then the Loxone update

**Comment by MatthiasBosch** [comment]
I found the problem.
I have checkt "nur Statusanzeige".
If you uncheck this upload it to the miniserver and the check again and upload again it works also with checked "nur Statusanzeige".

**Comment by raintonr** [comment]
"Status display only"... you can actually update these via a HTTP call.

Either way, looks like not a bug so closing.
