### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by jankir123** [UncleSamSwiss/ioBroker.loxone#56]
**Describe the bug**  
Since the update to version 2.0.2 I get disconnects from the miniserver from time to time. For some reason the adapter tries to connect so many times that the user will be temporarily blocked by the miniserver.

**Screenshots & Logfiles**  

loxone.0 | 2020-11-18 09:16:41.207 | error | (4599) Miniserver connection error: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
-- | -- | -- | --
loxone.0 | 2020-11-18 09:16:41.192 | info | (4599) Miniserver connected
loxone.0 | 2020-11-18 09:16:39.172 | info | (4599) connection closed
loxone.0 | 2020-11-18 09:16:39.170 | info | (4599) connection closed
loxone.0 | 2020-11-18 09:16:39.166 | error | (4599) Miniserver connection error: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
loxone.0 | 2020-11-18 09:16:39.143 | info | (4599) Miniserver connected
loxone.0 | 2020-11-18 09:16:37.806 | error | (4599) Unsupported state change: loxone.0.114e3254-01d3-650e-ffff10245f7c2cb9.value
loxone.0 | 2020-11-18 09:16:37.804 | error | (4599) Unsupported state change: loxone.0.114e320e-034b-d38e-ffff10245f7c2cb9.value
loxone.0 | 2020-11-18 09:16:37.119 | info | (4599) connection closed
loxone.0 | 2020-11-18 09:16:37.117 | info | (4599) connection closed
loxone.0 | 2020-11-18 09:16:36.914 | error | (4599) Miniserver connect failed
loxone.0 | 2020-11-18 09:16:36.735 | info | (4599) Miniserver connected
loxone.0 | 2020-11-18 09:16:34.970 | info | (4599) starting. Version 2.0.2 in /opt/iobroker/node_modules/iobroker.loxone, node: v10.23.0, js-controller: 3.1.6
host.ioBrokerPi | 2020-11-18 09:16:32.397 | info | instance system.adapter.loxone.0 started with pid 4599
host.ioBrokerPi | 2020-11-18 09:16:02.353 | info | Restart adapter system.adapter.loxone.0 because enabled
host.ioBrokerPi | 2020-11-18 09:16:02.351 | info | instance system.adapter.loxone.0 terminated with code 0 (NO_ERROR)
loxone.0 | 2020-11-18 09:16:01.792 | info | (4251) Terminated (NO_ERROR): Without reason
loxone.0 | 2020-11-18 09:16:01.789 | info | (4251) terminating
loxone.0 | 2020-11-18 09:16:01.779 | error | at addChunk (_stream_readable.js:288:12)
loxone.0 | 2020-11-18 09:16:01.779 | error | at Socket.emit (events.js:198:13)
loxone.0 | 2020-11-18 09:16:01.779 | error | at Socket.socketOnData (_http_client.js:451:20)
loxone.0 | 2020-11-18 09:16:01.779 | error | at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
loxone.0 | 2020-11-18 09:16:01.779 | error | at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
loxone.0 | 2020-11-18 09:16:01.779 | error | at ClientRequest.emit (events.js:198:13)
loxone.0 | 2020-11-18 09:16:01.779 | error | at ClientRequest.<anonymous> (/opt/iobroker/node_modules/websocket/lib/WebSocketClient.js:278:18)
loxone.0 | 2020-11-18 09:16:01.779 | error | at WebSocketClient.failHandshake (/opt/iobroker/node_modules/websocket/lib/WebSocketClient.js:339:10)
loxone.0 | 2020-11-18 09:16:01.779 | error | at WebSocketClient.emit (events.js:198:13)
loxone.0 | 2020-11-18 09:16:01.779 | error | at Connection.<anonymous> (/opt/iobroker/node_modules/node-lox-ws-api/lib/Connection.js:62:62)
loxone.0 | 2020-11-18 09:16:01.779 | error | (4251) TypeError: Cannot read property 'closeDescription' of undefined
loxone.0 | 2020-11-18 09:16:01.775 | error | (4251) uncaught exception: Cannot read property 'closeDescription' of undefined
loxone.0 | 2020-11-18 09:15:58.486 | info | (4251) starting. Version 2.0.2 in /opt/iobroker/node_modules/iobroker.loxone, node: v10.23.0, js-controller: 3.1.6

**Versions:**  
 - Adapter version: 2.0.2
 - JS-Controller version: 3.1.6
 - Node version: 10.23.0
 - Operating system: pi

**Comment by UncleSamSwiss** [comment]
Did you check #46 ?

**Comment by UncleSamSwiss** [comment]
No feedback, closing this issue.

If it happens again, feel free to reopen this issue.
