### ISSUE TITLE
Events cache should be replaced with queue & logic to process in guaranteed order

### ISSUE THREAD

**Issue by raintonr** [UncleSamSwiss/ioBroker.loxone#61]
Am looking at this code due to #58, which I notice can be circumvented if the adapter is restarted.

On investigating differences between reconnect and initial connect think that `cacheEvents` should probably be set to `true` when the connection is closed (in preparation for when the connection returns). Currently this flag is only set to `true` once on adapter startup, then set set `false` after the first load of structure file and never changed again.

So currently, as `cacheEvents` is left `false` on disconnect, when the connection is re-established many events are ignored while the structure file is loaded (this leads to many 'Unknown event' messages in log - but only seen when `debug` level is on).

I'm not sure if this is related to #58 but seems like a bug either way.

**Comment by raintonr** [comment]
In fact thinking more about this... there is *slight* a possibility that events are received during the replay and thus *may* execute out of order. It takes around 0.2s to replay the cache in my installation (RPi 3B+).

I guess that technically `eventsCache` should be a FIFO queue and the switch to bypass it should only be turned off once it is empty. Of course, there is a *tiny* possibility that something could be added to that queue between checking it's empty and turning the flag off so either a second check would be necessary or... well... would it be that big a deal/overhead to always place events in a FIFO and process from there?

**Comment by UncleSamSwiss** [comment]
I agree about the FIFO queue, but disagree about the check. As JavaScript is single-threaded there is no way for a variable to change "between two lines of code" except if there is an `await` in between.

About the first part (setting the cacheEvents flag), see my comment here: https://github.com/UncleSamSwiss/ioBroker.loxone/issues/58#issuecomment-739745847

**Comment by raintonr** [comment]
> I agree about the FIFO queue, but disagree about the check. As JavaScript is single-threaded there is no way for a variable to change "between two lines of code" except if there is an `await` in between.

**EXCEPT** ;)

We are developers. We write code that works in **EVERY** scenario, right?

**Comment by raintonr** [comment]
Sorry, thinking more about this should try and be a little more helpful... ;)

The `setState` method in ioBroker adapter is asynchronous has an optional callback.

From what I can tell, the Loxone adapter doesn't bother using a callback so just does `setState` and assumes it was successful, not caring about how long it takes to execute.

Again, from what I can tell, in ioBroker you can call `setState` 10 times and not be sure if these state changes will register in the order called. Let's say the underlying DB (Redis or whatever) has a delay writing the first state, but that same problem doesn't happen for the rest. Unlikely, but possible - imagine one Redis shard is particularly busy and has a delayed write.

Now, Loxone is throwing events down this connection and assuming they will execute in order. Sometimes if these are registered out of order it isn't a problem, but sometimes it is. Eg. I have various device statuses written to InfluxDB (based on when a state changes) where order is especially important (ie. if an `off` is written after an `on` in error my InfluxDb graphs would incorrectly show a device as `off` when it's really `on`).

Given all this, think it's not only desirable that events from Loxone are placed in a FIFO queue, but essential. And in fact, when processing events the adapter should `await` for one `setState` to complete before moving on to the next event as that's the only way to guarantee the correct order.

**Comment by UncleSamSwiss** [comment]
Note to self: have a look at https://www.npmjs.com/package/sequential-task-queue

**Comment by raintonr** [comment]
> Note to self: have a look at https://www.npmjs.com/package/sequential-task-queue

Yes - looks kindof interesting. Although is there a way to pause that task queue while still adding tasks?

Funnily enough I had a quick mess about with a FIFO rather than the cache array. This isn't particularly elegant but does the job and should guarantee the order of execution.

But none of this will ever be ideal until `handleEvent` returns a promise that can be waited on before moving on to the next item in the list.

**Comment by raintonr** [comment]
> But none of this will ever be ideal until `handleEvent` returns a promise that can be waited on before moving on to the next item in the list.

... which I have changed this morning. Please check it out, but looks good to me & should now guarantee order of execution of events from Loxone even after reconnect.

I would hope this fixes #58. I will leave this version of the code running and report back if I see any problems.

**Comment by UncleSamSwiss** [comment]
PR merged
