### ISSUE TITLE
Unsupported XY (whatever)

### ISSUE THREAD

**Issue by x-sven** [UncleSamSwiss/ioBroker.loxone#65]
Hi, 

is there any option/ chance to disable error messages of unsupported devices? 
I'm getting a large number of errors, but I will not care for it. However, they obfuscate relevant errors of other modules :-/

Thanks for the nice plugin!

Cheers, Sven

**Comment by UncleSamSwiss** [comment]
Currently there is no way to disable those warnings, but I will improve this in one of the next versions.

**Comment by UncleSamSwiss** [comment]
Log level will be "info".
