### ISSUE TITLE
Problem beim Schreiben von virtuellen Eingängen

### ISSUE THREAD

**Issue by JochenKoehler69** [UncleSamSwiss/ioBroker.loxone#8]
Hallo,
erstmal vielen Dank für den Adapter.
Ich hab erste Versuche damit unternommen und habe folgendes Problem:
Ich versuche, von meinem Landroid Maher ein paar Daten in den Miniserver zu schreiben. Bei vielen Daten funktioniert das auch - allerdings nicht bei der Betriebszeit. So sieht der Javascript Code aus:
    val=getState("landroid-s.0.mower.totalTime").val;
    console.log("Total Time "+val);
    setState("loxone.0.106bd1bd-011e-16e9-ffff912d5ec91829.value", val);    
Den Wert kann ich in iobroker  bei den Objects zwar sehen, aber der Miniserver wandelt ihn nicht in einen Anzeigewert um.
Irgendeine Idee?

Danke und Grüße
Jochen

**Comment by UncleSamSwiss** [comment]
Hallo Jochen

Was ist "landroid-s.0.mower.totalTime" für eine Art von Wert? Ist es ein reiner Integer oder eine Zeit im "HH:mm:ss" Format?
Siehst du im Log irgendwelche Fehlermeldungen?
Wenn du manuell einen Wert in "loxone.0.106bd1bd-011e-16e9-ffff912d5ec91829.value" schreibst (z.B. "123") funktioniert es dann?
Was ist "loxone.0.106bd1bd-011e-16e9-ffff912d5ec91829.value" für ein Control? Kannst du hier mal den Raw (siehe [Bug Reports](https://github.com/UncleSamSwiss/ioBroker.loxone#bug-reports-and-feature-requests)) posten?
Kannst du bitte auch das Log (im Level "Debug") hier posten, dann sehe ich eventuell etwas mehr.

/UncleSam

**Comment by JochenKoehler69** [comment]
Hallo Samuel,

 

danke für die schnelle Antwort.

Hab das Problem dadurch gelöst, dass ich in LoxConfig die Eingabetype auf „Schieber“ geändert habe. Vorher war es auf „Links-Rechts-Tasten“.

Seltsames Verhalten vom Miniserver …

 

Schönen Sonntag noch!

 

Grüße

Jochen

 

Von: Samuel Weibel [mailto:notifications@github.com] 
Gesendet: Sonntag, 15. Oktober 2017 14:09
An: UncleSamSwiss/ioBroker.loxone <ioBroker.loxone@noreply.github.com>
Cc: JochenKoehler69 <jochen.koehler@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [UncleSamSwiss/ioBroker.loxone] Problem beim Schreiben von virtuellen Eingängen (#8)

 

Hallo Jochen

Was ist "landroid-s.0.mower.totalTime" für eine Art von Wert? Ist es ein reiner Integer oder eine Zeit im "HH:mm:ss" Format?
Siehst du im Log irgendwelche Fehlermeldungen?
Wenn du manuell einen Wert in "loxone.0.106bd1bd-011e-16e9-ffff912d5ec91829.value" schreibst (z.B. "123") funktioniert es dann?
Was ist "loxone.0.106bd1bd-011e-16e9-ffff912d5ec91829.value" für ein Control? Kannst du hier mal den Raw (siehe Bug Reports <https://github.com/UncleSamSwiss/ioBroker.loxone#bug-reports-and-feature-requests> ) posten?
Kannst du bitte auch das Log (im Level "Debug") hier posten, dann sehe ich eventuell etwas mehr.

/UncleSam

**Comment by UncleSamSwiss** [comment]
Gehen wir mal davon aus, dass das ein Bug im Loxone Miniserver ist.
