### ISSUE TITLE
js or ts ?

### ISSUE THREAD

**Issue by Ikswoknib** [UncleSamSwiss/ioBroker.loxone#88]
Hello,

i would like to implement some of the missing controls but i am a bit confused.
In the build folder there are .js files for each control but in the src folder there are .ts files for each control.
So what is right then ?
In the documentation there is written that everything is changed from js to ts.

I just got some of the missing controls working by adding the .js files in the build folder of my copy of the repository and then installing it from this. So is .js okay?

best regards

**Comment by UncleSamSwiss** [comment]
Please create your code in TypeScript and then call `npm run build` to create the JavaScript code.

Please also have a look at the [two (pending) PRs](https://github.com/UncleSamSwiss/ioBroker.loxone/pulls) from @raintonr (just not that you do the same work again).

**Comment by raintonr** [comment]
Yes, we've discussed this. JS is a 'compiled' output and IMHO should therefore not be stored in Git.

@Ikswoknib Out of interest, which controls are you going to implement?

**Comment by UncleSamSwiss** [comment]
I completely agree; in any professional project I've worked for, we always excluded the compiled output.

Unfortunately it wouldn't be possible to install the adapter from Github (instead of NPM) if the JavaScript code weren't included. @AlCalzone is working on a solution for this, but that's for the long term.

**Comment by raintonr** [comment]
> Unfortunately it wouldn't be possible to install the adapter from Github (instead of NPM) if the JavaScript code weren't included.

True, but anyone who is doing this surely won't mind typing `npm run build` ;)

**Comment by AlCalzone** [comment]
> True, but anyone who is doing this surely won't mind typing `npm run build` ;)

Except you don't want to include the devDependencies for every adapter :)

**Comment by UncleSamSwiss** [comment]
> > Unfortunately it wouldn't be possible to install the adapter from Github (instead of NPM) if the JavaScript code weren't included.
> 
> True, but anyone who is doing this surely won't mind typing `npm run build` ;)

Not true at all: installing an adapter from GitHub can be done with two clicks from Admin. Calling `npm run build` requires you to be on the system, find the right directory and then call the command. Additionally, this would only work for adapter code and not for Admin UI (React) as you would additionally have to call `iobroker upload` again.

**Comment by Ikswoknib** [comment]
I have implemented the following on my Version, but at the time in js only, so i have to do it in ts again:
Radio
TextState
UpDownAnalog
UpDownDigital

All are working for me, they are quite not too complex, so a good thing for me to learn ;-)

**Comment by UncleSamSwiss** [comment]
To start, just copy over the code from JavaScript to the .ts file. Theoretically any JavaScript is valid TypeScript, but we have some stricter rules in this project.

**Comment by UncleSamSwiss** [comment]
The question was answered. Closing issue.
